// SPDX-License-Identifier: Apache-2.0
// @category RV220W
// Usage: RV220WUBootExport.java <output-dir>
import ghidra.app.decompiler.*;
import ghidra.app.script.GhidraScript;
import ghidra.framework.options.Options;
import ghidra.program.model.listing.*;
import ghidra.program.model.symbol.*;
import java.io.*;
import java.nio.charset.StandardCharsets;
import java.nio.file.*;
import java.security.MessageDigest;
import java.util.*;
public class RV220WUBootExport extends GhidraScript {
  static String cl(String s){return s==null?"":s.replace("\\","\\\\").replace("\t","\\t").replace("\r","\\r").replace("\n","\\n");}
  static String safe(String s){String x=s.replaceAll("[^A-Za-z0-9_.-]+","_");return x.length()>100?x.substring(0,100):x;}
  static String sha(String s)throws Exception{MessageDigest m=MessageDigest.getInstance("SHA-256");StringBuilder b=new StringBuilder();for(byte v:m.digest(s.getBytes(StandardCharsets.UTF_8)))b.append(String.format("%02x",v));return b.toString();}
  String subsystem(String n){String x=n.toLowerCase(Locale.ROOT);if(x.contains("bcm53115")||x.contains("bcmmii"))return"bcm53115-switch";if(x.contains("mdio")||x.contains("mii"))return"mdio";if(x.contains("gpio")||x.contains("button"))return"gpio-button";if(x.contains("flash")||x.contains("env"))return"nor-environment";if(x.contains("mac"))return"mac-address";if(x.startsWith("do_"))return"u-boot-command";if(x.contains("board"))return"board-init";return"bootloader-support";}
  List<String> strings(Function fn){LinkedHashSet<String>o=new LinkedHashSet<>();Listing l=currentProgram.getListing();ReferenceManager rm=currentProgram.getReferenceManager();InstructionIterator it=l.getInstructions(fn.getBody(),true);while(it.hasNext()){Instruction in=it.next();for(Reference r:rm.getReferencesFrom(in.getAddress())){Data d=l.getDataAt(r.getToAddress());if(d==null)d=l.getDataContaining(r.getToAddress());if(d!=null&&d.getValue()instanceof String){String s=((String)d.getValue()).replace("\u0000","");if(!s.isEmpty())o.add(s);}}}return new ArrayList<>(o);}
  @Override public void run()throws Exception{String[]a=getScriptArgs();if(a.length!=1)throw new IllegalArgumentException("output-dir");Path out=Paths.get(a[0]),cd=out.resolve("decompiled"),ad=out.resolve("assembly");Files.createDirectories(cd);Files.createDirectories(ad);DecompInterface di=new DecompInterface();di.toggleCCode(true);di.toggleSyntaxTree(true);di.setSimplificationStyle("decompile");if(!di.openProgram(currentProgram))throw new IllegalStateException("decompiler open failed");
    try(BufferedWriter fi=Files.newBufferedWriter(out.resolve("functions.tsv"),StandardCharsets.UTF_8);BufferedWriter cg=Files.newBufferedWriter(out.resolve("callgraph.tsv"),StandardCharsets.UTF_8);BufferedWriter st=Files.newBufferedWriter(out.resolve("strings.tsv"),StandardCharsets.UTF_8);BufferedWriter ff=Files.newBufferedWriter(out.resolve("decompile-failures.tsv"),StandardCharsets.UTF_8)){fi.write("entry\tname\tsubsystem\tsize\tsource\tdecompile\tsha256\tcallers\tcallees\tstrings\tc_file\tasm_file\n");cg.write("caller_entry\tcaller_name\tcallee_entry\tcallee_name\n");st.write("function_entry\tfunction_name\tstring\n");ff.write("entry\tname\treason\n");int total=0,ok=0,bad=0;Listing listing=currentProgram.getListing();
      for(Function fn:currentProgram.getFunctionManager().getFunctions(true)){monitor.checkCancelled();total++;String n=fn.getName(),q=fn.getName(true),prefix=fn.getEntryPoint()+"_"+safe(q);Set<Function>ca=new LinkedHashSet<>(),ce=new LinkedHashSet<>();for(Function x:fn.getCallingFunctions(monitor))ca.add(x);for(Function x:fn.getCalledFunctions(monitor))ce.add(x);for(Function x:ce)cg.write(fn.getEntryPoint()+"\t"+cl(q)+"\t"+x.getEntryPoint()+"\t"+cl(x.getName(true))+"\n");List<String>ss=strings(fn);for(String s:ss)st.write(fn.getEntryPoint()+"\t"+cl(q)+"\t"+cl(s)+"\n");String c="",status="external",reason="";if(!fn.isExternal()){try{DecompileResults dr=di.decompileFunction(fn,2,monitor);if(dr!=null&&dr.decompileCompleted()&&dr.getDecompiledFunction()!=null){c=dr.getDecompiledFunction().getC();status="success";ok++;}else{status="failed";reason=dr==null?"null":dr.getErrorMessage();bad++;}}catch(Exception e){status="exception";reason=e.toString();bad++;}}
        String cf="decompiled/"+prefix+".c",af="assembly/"+prefix+".asm";String ann=fn.getComment();if(ann==null)ann="";StringBuilder h=new StringBuilder("/*\n * Ghidra reconstructed C; not original Cisco source.\n * RV220W boot-chain/U-Boot analysis v1.1.0\n * Entry: "+fn.getEntryPoint()+"\n * Function: "+q+"\n * Subsystem: "+subsystem(q)+"\n *\n");for(String line:ann.split("\\R"))h.append(" * ").append(line).append("\n");h.append(" */\n");Files.writeString(out.resolve(cf),h+(c.isEmpty()?"/* No C output: "+status+" "+reason+" */\n":c),StandardCharsets.UTF_8);try(BufferedWriter w=Files.newBufferedWriter(out.resolve(af),StandardCharsets.UTF_8)){w.write("# RV220W U-Boot v1.1.0 entry="+fn.getEntryPoint()+" function="+q+"\n");InstructionIterator ii=listing.getInstructions(fn.getBody(),true);while(ii.hasNext()){Instruction ins=ii.next();w.write(ins.getAddress()+"\t"+ins+"\n");}}
        if(status.equals("failed")||status.equals("exception"))ff.write(fn.getEntryPoint()+"\t"+cl(q)+"\t"+cl(reason)+"\n");fi.write(fn.getEntryPoint()+"\t"+cl(q)+"\t"+subsystem(q)+"\t"+fn.getBody().getNumAddresses()+"\t"+fn.getSymbol().getSource()+"\t"+status+"\t"+sha(c)+"\t"+ca.size()+"\t"+ce.size()+"\t"+ss.size()+"\t"+cf+"\t"+af+"\n");if(total%50==0)println("export-progress="+total+" ok="+ok+" bad="+bad);}
      Files.writeString(out.resolve("summary.tsv"),"key\tvalue\nanalysis_version\tv1.1.0\nprogram\t"+currentProgram.getName()+"\nprocessor\t"+currentProgram.getLanguageID()+"\nfunction_count\t"+total+"\ndecompile_success\t"+ok+"\ndecompile_failure\t"+bad+"\n",StandardCharsets.UTF_8);Options o=currentProgram.getOptions("Program Information");o.setLong("RV220W Export Functions",total);o.setLong("RV220W Export Success",ok);o.setLong("RV220W Export Failures",bad);println("functions="+total+" success="+ok+" failure="+bad);}
  }
}
