// SPDX-License-Identifier: Apache-2.0
// @category RV220W
// Usage: RV220WWholeProgramPass.java <output-dir> <module-id>
import ghidra.app.decompiler.*;
import ghidra.app.script.GhidraScript;
import ghidra.framework.options.Options;
import ghidra.program.model.address.*;
import ghidra.program.model.listing.*;
import ghidra.program.model.symbol.*;
import java.io.*;
import java.nio.charset.StandardCharsets;
import java.nio.file.*;
import java.security.MessageDigest;
import java.util.*;

public class RV220WWholeProgramPass extends GhidraScript {
    private static final String VERSION="rv220w-stock-modules-v1.0.0";
    private static String clean(String s){if(s==null)return"";return s.replace("\\","\\\\").replace("\t","\\t").replace("\r","\\r").replace("\n","\\n");}
    private static String safe(String s){if(s==null||s.isEmpty())return"unnamed";String x=s.replaceAll("[^A-Za-z0-9_.-]+","_");return x.length()>120?x.substring(0,120):x;}
    private static String sha256(String s)throws Exception{MessageDigest md=MessageDigest.getInstance("SHA-256");byte[]b=md.digest(s.getBytes(StandardCharsets.UTF_8));StringBuilder x=new StringBuilder();for(byte v:b)x.append(String.format("%02x",v));return x.toString();}
    private String subsystem(String q){String n=q.toLowerCase(Locale.ROOT);if(n.contains("vlan")||n.contains("bcm5398")||n.contains("wanport")||n.contains("brcmtag"))return"bcm53115-switch";if(n.contains("mdio")||n.contains("mii")||n.contains("phy"))return"mdio-pseudophy";if(n.contains("ipfwd")||n.contains("offload")||n.contains("flow"))return"octeon-offload";if(n.contains("cvm_oct")||n.contains("ether")||n.contains("rgmii")||n.contains("sgmii")||n.contains("xaui"))return"octeon-ethernet";if(n.contains("led")||n.contains("blink")||n.contains("gpio"))return"led-gpio";if(n.contains("button")||n.contains("reset"))return"reset-button";if(n.contains("init_module")||n.contains("cleanup_module"))return"module-lifecycle";if(n.startsWith("fun_"))return"unresolved-local";return"module-support";}
    private List<String> stringRefs(Function fn){LinkedHashSet<String>out=new LinkedHashSet<>();Listing l=currentProgram.getListing();ReferenceManager rm=currentProgram.getReferenceManager();InstructionIterator it=l.getInstructions(fn.getBody(),true);while(it.hasNext()){Instruction ins=it.next();for(Reference r:rm.getReferencesFrom(ins.getAddress())){Data d=l.getDataAt(r.getToAddress());if(d==null)d=l.getDataContaining(r.getToAddress());if(d!=null&&d.getValue()instanceof String){String s=((String)d.getValue()).replace("\u0000","");if(!s.isEmpty())out.add(s);}}}return new ArrayList<>(out);}
    private String names(Collection<Function>fs,int max){ArrayList<String>x=new ArrayList<>();for(Function f:fs)x.add(f.getName(true)+"@"+f.getEntryPoint());Collections.sort(x);if(x.size()>max){int m=x.size()-max;x=new ArrayList<>(x.subList(0,max));x.add("...+"+m);}return String.join(";",x);}
    @Override public void run() throws Exception {
        String[]a=getScriptArgs();if(a.length!=2)throw new IllegalArgumentException("output-dir module-id");Path out=Paths.get(a[0]);String module=a[1];Path cdir=out.resolve("decompiled"),adir=out.resolve("assembly");Files.createDirectories(cdir);Files.createDirectories(adir);
        try(BufferedWriter idx=Files.newBufferedWriter(out.resolve("functions.tsv"),StandardCharsets.UTF_8);BufferedWriter calls=Files.newBufferedWriter(out.resolve("callgraph.tsv"),StandardCharsets.UTF_8);BufferedWriter strs=Files.newBufferedWriter(out.resolve("strings.tsv"),StandardCharsets.UTF_8);BufferedWriter fails=Files.newBufferedWriter(out.resolve("decompile-failures.tsv"),StandardCharsets.UTF_8);BufferedWriter ext=Files.newBufferedWriter(out.resolve("external-symbols.tsv"),StandardCharsets.UTF_8)){
            idx.write("entry\tname\tqualified_name\tsubsystem\tevidence\tsize\tparameters\tlocals\tsource\tthunk\texternal\tdecompile\tdecompile_sha256\tcaller_count\tcallee_count\tstring_count\tc_file\tasm_file\n");calls.write("caller_entry\tcaller_name\tcallee_entry\tcallee_name\n");strs.write("function_entry\tfunction_name\tstring\n");fails.write("entry\tname\treason\n");ext.write("entry\tname\tqualified_name\n");
            DecompInterface decomp=new DecompInterface();decomp.toggleCCode(true);decomp.toggleSyntaxTree(true);decomp.setSimplificationStyle("decompile");if(!decomp.openProgram(currentProgram))throw new IllegalStateException("decompiler open failed");FunctionManager fm=currentProgram.getFunctionManager();Listing listing=currentProgram.getListing();int total=0,success=0,failure=0,external=0;
            for(Function fn:fm.getFunctions(true)){monitor.checkCancelled();total++;String name=fn.getName(),q=fn.getName(true),sub=subsystem(q);boolean auto=name.startsWith("FUN_")||fn.getSymbol().getSource()==SourceType.DEFAULT;String evidence=fn.isExternal()?"external":fn.isThunk()?"thunk":auto?"analysis-auto":"retained-or-recovered-symbol";if(fn.isExternal()){external++;ext.write(fn.getEntryPoint()+"\t"+clean(name)+"\t"+clean(q)+"\n");}
                Set<Function>callerSet=new LinkedHashSet<>(),calleeSet=new LinkedHashSet<>();for(Function f:fn.getCallingFunctions(monitor))callerSet.add(f);for(Function f:fn.getCalledFunctions(monitor))calleeSet.add(f);for(Function callee:calleeSet)calls.write(fn.getEntryPoint()+"\t"+clean(q)+"\t"+callee.getEntryPoint()+"\t"+clean(callee.getName(true))+"\n");List<String>sr=stringRefs(fn);for(String s:sr)strs.write(fn.getEntryPoint()+"\t"+clean(q)+"\t"+clean(s)+"\n");
                String prefix=fn.getEntryPoint()+"_"+safe(q),cfile="decompiled/"+prefix+".c",afile="assembly/"+prefix+".asm";String ctext="",status="not-attempted",reason="";if(fn.isExternal())status="external";else try{DecompileResults dr=decomp.decompileFunction(fn,10,monitor);if(dr!=null&&dr.decompileCompleted()&&dr.getDecompiledFunction()!=null){ctext=dr.getDecompiledFunction().getC();status="success";success++;}else{status="failed";reason=dr==null?"null-results":clean(dr.getErrorMessage());failure++;}}catch(Exception e){status="exception";reason=clean(e.toString());failure++;}
                String semantic=fn.getComment()==null?"":fn.getComment();String header="/*\n * Ghidra reconstructed C; not original Cisco source.\n * Analysis: "+VERSION+"\n * Module: "+module+"\n * Entry: "+fn.getEntryPoint()+"\n * Function: "+q+"\n * Subsystem: "+sub+"\n * Evidence: "+evidence+"\n *\n * Embedded Ghidra annotation:\n";StringBuilder hb=new StringBuilder(header);for(String line:semantic.split("\\R"))hb.append(" * ").append(line).append("\n");hb.append(" */\n");Files.writeString(out.resolve(cfile),hb+(ctext.isEmpty()?"/* no decompilation: "+status+" "+reason+" */\n":ctext),StandardCharsets.UTF_8);if(status.equals("failed")||status.equals("exception"))fails.write(fn.getEntryPoint()+"\t"+clean(q)+"\t"+reason+"\n");
                try(BufferedWriter aw=Files.newBufferedWriter(out.resolve(afile),StandardCharsets.UTF_8)){aw.write("# "+VERSION+" module="+module+" entry="+fn.getEntryPoint()+" function="+q+"\n");InstructionIterator ii=listing.getInstructions(fn.getBody(),true);while(ii.hasNext()){Instruction ins=ii.next();aw.write(ins.getAddress()+"\t"+ins+"\n");}}
                long size=fn.getBody()==null?0:fn.getBody().getNumAddresses();idx.write(fn.getEntryPoint()+"\t"+clean(name)+"\t"+clean(q)+"\t"+sub+"\t"+evidence+"\t"+size+"\t"+fn.getParameterCount()+"\t"+fn.getLocalVariables().length+"\t"+fn.getSymbol().getSource()+"\t"+fn.isThunk()+"\t"+fn.isExternal()+"\t"+status+"\t"+sha256(ctext)+"\t"+callerSet.size()+"\t"+calleeSet.size()+"\t"+sr.size()+"\t"+cfile+"\t"+afile+"\n");
                String marker="\n\nRV220W WHOLE-PROGRAM EXPORT\nDecompiler status: "+status+"\nCallers: "+names(callerSet,20)+"\nCallees: "+names(calleeSet,30)+"\nString evidence: "+(sr.isEmpty()?"none":String.join(" | ",sr));fn.setComment(semantic+marker);
            }
            Files.writeString(out.resolve("summary.tsv"),"key\tvalue\nmodule\t"+module+"\nanalysis_version\t"+VERSION+"\nprogram\t"+currentProgram.getName()+"\nprocessor\t"+currentProgram.getLanguageID()+"\nfunction_count\t"+total+"\ndecompile_success\t"+success+"\ndecompile_failure\t"+failure+"\nexternal_count\t"+external+"\n",StandardCharsets.UTF_8);
            Options o=currentProgram.getOptions("Program Information");o.setString("RV220W Whole Program Export",VERSION);o.setLong("RV220W Export Function Count",total);o.setLong("RV220W Export Decompile Success",success);o.setLong("RV220W Export Decompile Failure",failure);println("module="+module+" functions="+total+" success="+success+" failure="+failure+" external="+external);
        }
    }
}
