#!/bin/sh
# RAM-only LAN DSA validation network. Ports appear as lan1..lan4.
# Remove generic pre-DSA bridge/device definitions before creating the DSA bridge.
uci -q delete network.wan
uci -q delete network.wan6
uci -q delete network.lan
uci -q delete network.br_lan

while :; do
    section=$(uci -q show network | sed -n "s/^\(network\.@device\[[0-9][0-9]*\]\)\.name='br-lan'$/\1/p" | head -n 1)
    [ -n "$section" ] || break
    uci -q delete "$section" || break
done

uci set network.br_lan='device'
uci set network.br_lan.name='br-lan'
uci set network.br_lan.type='bridge'
uci add_list network.br_lan.ports='lan1'
uci add_list network.br_lan.ports='lan2'
uci add_list network.br_lan.ports='lan3'
uci add_list network.br_lan.ports='lan4'
uci set network.br_lan.stp='0'
uci set network.lan='interface'
uci set network.lan.device='br-lan'
uci set network.lan.proto='static'
uci set network.lan.ipaddr='192.168.240.2'
uci set network.lan.netmask='255.255.255.0'
uci set network.lan.gateway=''
uci set network.lan.dns=''
uci commit network
logger -t rv220w 'RAM-only LAN DSA profile: stale eth0 bridge removed; lan1-lan4 bridged at 192.168.240.2; WAN excluded'
exit 0
