#!/bin/sh
# Deterministic direct-link validation network; initramfs changes vanish on reboot.
uci -q set system.@system[0].hostname='rv220w-validation'
uci -q set network.lan.proto='static'
uci -q set network.lan.ipaddr='192.168.240.2'
uci -q set network.lan.netmask='255.255.255.0'
uci -q set network.lan.gateway=''
uci -q set network.lan.dns=''
uci -q commit system
uci -q commit network
logger -t rv220w 'RAM-validation image: LAN 192.168.240.2/24; no persistent-flash workflow enabled'
exit 0
