#!/bin/sh
# RAM-only dual-conduit DSA validation network.
# LAN remains 192.168.240.2/24; WAN is isolated at 192.168.241.2/24.
# No gateway, DNS, firewall, DHCP, NAT, or forwarding is configured.
uci -q delete network.wan
uci -q delete network.wan6
uci -q delete network.lan
uci -q delete network.br_lan

while :; do
	section=$(uci -q show network | sed -n "s/^\(network\.@device\[[0-9][0-9]*\]\)\.name='br-lan'$/\1/p" | head -n 1)
	[ -n "$section" ] || break
	uci -q delete "$section" || break
done

uci set network.br_lan='device'
uci set network.br_lan.name='br-lan'
uci set network.br_lan.type='bridge'
uci add_list network.br_lan.ports='lan1'
uci add_list network.br_lan.ports='lan2'
uci add_list network.br_lan.ports='lan3'
uci add_list network.br_lan.ports='lan4'
uci set network.br_lan.stp='0'

uci set network.lan='interface'
uci set network.lan.device='br-lan'
uci set network.lan.proto='static'
uci set network.lan.ipaddr='192.168.240.2'
uci set network.lan.netmask='255.255.255.0'
uci set network.lan.gateway=''
uci set network.lan.dns=''

uci set network.wan='interface'
uci set network.wan.device='wan'
uci set network.wan.proto='static'
uci set network.wan.ipaddr='192.168.241.2'
uci set network.wan.netmask='255.255.255.0'
uci set network.wan.gateway=''
uci set network.wan.dns=''

uci commit network
logger -t rv220w 'RAM-only dual DSA profile: lan1-lan4 -> br-lan 192.168.240.2; wan isolated at 192.168.241.2; routing/firewall disabled'
exit 0
